/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ValidationCaseRouteImport } from './routes/validation-case'
import { Route as SyntheticNetworkStudyRouteImport } from './routes/synthetic-network-study'
import { Route as ServiceRouteImport } from './routes/service'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PowerFinderRouteImport } from './routes/power-finder'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PilotRequestsRouteImport } from './routes/pilot-requests'
import { Route as PilotReadyRouteImport } from './routes/pilot-ready'
import { Route as PilotRouteImport } from './routes/pilot'
import { Route as OperationsRouteImport } from './routes/operations'
import { Route as HydrogenIndustryRouteImport } from './routes/hydrogen-industry'
import { Route as EvidenceReviewRouteImport } from './routes/evidence-review'
import { Route as EvidenceRouteImport } from './routes/evidence'
import { Route as EnergyStorageRouteImport } from './routes/energy-storage'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as DataSourcesRouteImport } from './routes/data-sources'
import { Route as DataCentresRouteImport } from './routes/data-centres'
import { Route as ActivationRouteImport } from './routes/activation'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubmissionPackageIdRouteImport } from './routes/submission-package.$id'
import { Route as PortfolioIdRouteImport } from './routes/portfolio.$id'
import { Route as PilotCaseIdRouteImport } from './routes/pilot-case.$id'
import { Route as OperatorReviewIdRouteImport } from './routes/operator-review.$id'
import { Route as OperationsIdRouteImport } from './routes/operations.$id'
import { Route as CapacityDossiersIdRouteImport } from './routes/capacity-dossiers.$id'
import { Route as AssessmentsNewRouteImport } from './routes/assessments.new'
import { Route as AssessmentsIdRouteImport } from './routes/assessments.$id'
import { Route as ActivationIdRouteImport } from './routes/activation.$id'
import { Route as ApiPowerFinderViewportRouteImport } from './routes/api.power-finder.viewport'
import { Route as ApiPowerFinderStudyRouteImport } from './routes/api.power-finder.study'
import { Route as ApiPowerFinderScenarioRouteImport } from './routes/api.power-finder.scenario'
import { Route as ApiPowerFinderTileZXYRouteImport } from './routes/api.power-finder.tile.$z.$x.$y'

const ValidationCaseRoute = ValidationCaseRouteImport.update({
  id: '/validation-case',
  path: '/validation-case',
  getParentRoute: () => rootRouteImport,
} as any)
const SyntheticNetworkStudyRoute = SyntheticNetworkStudyRouteImport.update({
  id: '/synthetic-network-study',
  path: '/synthetic-network-study',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceRoute = ServiceRouteImport.update({
  id: '/service',
  path: '/service',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PowerFinderRoute = PowerFinderRouteImport.update({
  id: '/power-finder',
  path: '/power-finder',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PilotRequestsRoute = PilotRequestsRouteImport.update({
  id: '/pilot-requests',
  path: '/pilot-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const PilotReadyRoute = PilotReadyRouteImport.update({
  id: '/pilot-ready',
  path: '/pilot-ready',
  getParentRoute: () => rootRouteImport,
} as any)
const PilotRoute = PilotRouteImport.update({
  id: '/pilot',
  path: '/pilot',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsRoute = OperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const HydrogenIndustryRoute = HydrogenIndustryRouteImport.update({
  id: '/hydrogen-industry',
  path: '/hydrogen-industry',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceReviewRoute = EvidenceReviewRouteImport.update({
  id: '/evidence-review',
  path: '/evidence-review',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceRoute = EvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const EnergyStorageRoute = EnergyStorageRouteImport.update({
  id: '/energy-storage',
  path: '/energy-storage',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DataSourcesRoute = DataSourcesRouteImport.update({
  id: '/data-sources',
  path: '/data-sources',
  getParentRoute: () => rootRouteImport,
} as any)
const DataCentresRoute = DataCentresRouteImport.update({
  id: '/data-centres',
  path: '/data-centres',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivationRoute = ActivationRouteImport.update({
  id: '/activation',
  path: '/activation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmissionPackageIdRoute = SubmissionPackageIdRouteImport.update({
  id: '/submission-package/$id',
  path: '/submission-package/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioIdRoute = PortfolioIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PortfolioRoute,
} as any)
const PilotCaseIdRoute = PilotCaseIdRouteImport.update({
  id: '/pilot-case/$id',
  path: '/pilot-case/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorReviewIdRoute = OperatorReviewIdRouteImport.update({
  id: '/operator-review/$id',
  path: '/operator-review/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsIdRoute = OperationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OperationsRoute,
} as any)
const CapacityDossiersIdRoute = CapacityDossiersIdRouteImport.update({
  id: '/capacity-dossiers/$id',
  path: '/capacity-dossiers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentsNewRoute = AssessmentsNewRouteImport.update({
  id: '/assessments/new',
  path: '/assessments/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentsIdRoute = AssessmentsIdRouteImport.update({
  id: '/assessments/$id',
  path: '/assessments/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivationIdRoute = ActivationIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ActivationRoute,
} as any)
const ApiPowerFinderViewportRoute = ApiPowerFinderViewportRouteImport.update({
  id: '/api/power-finder/viewport',
  path: '/api/power-finder/viewport',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPowerFinderStudyRoute = ApiPowerFinderStudyRouteImport.update({
  id: '/api/power-finder/study',
  path: '/api/power-finder/study',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPowerFinderScenarioRoute = ApiPowerFinderScenarioRouteImport.update({
  id: '/api/power-finder/scenario',
  path: '/api/power-finder/scenario',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPowerFinderTileZXYRoute = ApiPowerFinderTileZXYRouteImport.update({
  id: '/api/power-finder/tile/$z/$x/$y',
  path: '/api/power-finder/tile/$z/$x/$y',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activation': typeof ActivationRouteWithChildren
  '/data-centres': typeof DataCentresRoute
  '/data-sources': typeof DataSourcesRoute
  '/demo': typeof DemoRoute
  '/energy-storage': typeof EnergyStorageRoute
  '/evidence': typeof EvidenceRoute
  '/evidence-review': typeof EvidenceReviewRoute
  '/hydrogen-industry': typeof HydrogenIndustryRoute
  '/operations': typeof OperationsRouteWithChildren
  '/pilot': typeof PilotRoute
  '/pilot-ready': typeof PilotReadyRoute
  '/pilot-requests': typeof PilotRequestsRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/power-finder': typeof PowerFinderRoute
  '/reports': typeof ReportsRoute
  '/service': typeof ServiceRoute
  '/synthetic-network-study': typeof SyntheticNetworkStudyRoute
  '/validation-case': typeof ValidationCaseRoute
  '/activation/$id': typeof ActivationIdRoute
  '/assessments/$id': typeof AssessmentsIdRoute
  '/assessments/new': typeof AssessmentsNewRoute
  '/capacity-dossiers/$id': typeof CapacityDossiersIdRoute
  '/operations/$id': typeof OperationsIdRoute
  '/operator-review/$id': typeof OperatorReviewIdRoute
  '/pilot-case/$id': typeof PilotCaseIdRoute
  '/portfolio/$id': typeof PortfolioIdRoute
  '/submission-package/$id': typeof SubmissionPackageIdRoute
  '/api/power-finder/scenario': typeof ApiPowerFinderScenarioRoute
  '/api/power-finder/study': typeof ApiPowerFinderStudyRoute
  '/api/power-finder/viewport': typeof ApiPowerFinderViewportRoute
  '/api/power-finder/tile/$z/$x/$y': typeof ApiPowerFinderTileZXYRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activation': typeof ActivationRouteWithChildren
  '/data-centres': typeof DataCentresRoute
  '/data-sources': typeof DataSourcesRoute
  '/demo': typeof DemoRoute
  '/energy-storage': typeof EnergyStorageRoute
  '/evidence': typeof EvidenceRoute
  '/evidence-review': typeof EvidenceReviewRoute
  '/hydrogen-industry': typeof HydrogenIndustryRoute
  '/operations': typeof OperationsRouteWithChildren
  '/pilot': typeof PilotRoute
  '/pilot-ready': typeof PilotReadyRoute
  '/pilot-requests': typeof PilotRequestsRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/power-finder': typeof PowerFinderRoute
  '/reports': typeof ReportsRoute
  '/service': typeof ServiceRoute
  '/synthetic-network-study': typeof SyntheticNetworkStudyRoute
  '/validation-case': typeof ValidationCaseRoute
  '/activation/$id': typeof ActivationIdRoute
  '/assessments/$id': typeof AssessmentsIdRoute
  '/assessments/new': typeof AssessmentsNewRoute
  '/capacity-dossiers/$id': typeof CapacityDossiersIdRoute
  '/operations/$id': typeof OperationsIdRoute
  '/operator-review/$id': typeof OperatorReviewIdRoute
  '/pilot-case/$id': typeof PilotCaseIdRoute
  '/portfolio/$id': typeof PortfolioIdRoute
  '/submission-package/$id': typeof SubmissionPackageIdRoute
  '/api/power-finder/scenario': typeof ApiPowerFinderScenarioRoute
  '/api/power-finder/study': typeof ApiPowerFinderStudyRoute
  '/api/power-finder/viewport': typeof ApiPowerFinderViewportRoute
  '/api/power-finder/tile/$z/$x/$y': typeof ApiPowerFinderTileZXYRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activation': typeof ActivationRouteWithChildren
  '/data-centres': typeof DataCentresRoute
  '/data-sources': typeof DataSourcesRoute
  '/demo': typeof DemoRoute
  '/energy-storage': typeof EnergyStorageRoute
  '/evidence': typeof EvidenceRoute
  '/evidence-review': typeof EvidenceReviewRoute
  '/hydrogen-industry': typeof HydrogenIndustryRoute
  '/operations': typeof OperationsRouteWithChildren
  '/pilot': typeof PilotRoute
  '/pilot-ready': typeof PilotReadyRoute
  '/pilot-requests': typeof PilotRequestsRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/power-finder': typeof PowerFinderRoute
  '/reports': typeof ReportsRoute
  '/service': typeof ServiceRoute
  '/synthetic-network-study': typeof SyntheticNetworkStudyRoute
  '/validation-case': typeof ValidationCaseRoute
  '/activation/$id': typeof ActivationIdRoute
  '/assessments/$id': typeof AssessmentsIdRoute
  '/assessments/new': typeof AssessmentsNewRoute
  '/capacity-dossiers/$id': typeof CapacityDossiersIdRoute
  '/operations/$id': typeof OperationsIdRoute
  '/operator-review/$id': typeof OperatorReviewIdRoute
  '/pilot-case/$id': typeof PilotCaseIdRoute
  '/portfolio/$id': typeof PortfolioIdRoute
  '/submission-package/$id': typeof SubmissionPackageIdRoute
  '/api/power-finder/scenario': typeof ApiPowerFinderScenarioRoute
  '/api/power-finder/study': typeof ApiPowerFinderStudyRoute
  '/api/power-finder/viewport': typeof ApiPowerFinderViewportRoute
  '/api/power-finder/tile/$z/$x/$y': typeof ApiPowerFinderTileZXYRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activation'
    | '/data-centres'
    | '/data-sources'
    | '/demo'
    | '/energy-storage'
    | '/evidence'
    | '/evidence-review'
    | '/hydrogen-industry'
    | '/operations'
    | '/pilot'
    | '/pilot-ready'
    | '/pilot-requests'
    | '/portfolio'
    | '/power-finder'
    | '/reports'
    | '/service'
    | '/synthetic-network-study'
    | '/validation-case'
    | '/activation/$id'
    | '/assessments/$id'
    | '/assessments/new'
    | '/capacity-dossiers/$id'
    | '/operations/$id'
    | '/operator-review/$id'
    | '/pilot-case/$id'
    | '/portfolio/$id'
    | '/submission-package/$id'
    | '/api/power-finder/scenario'
    | '/api/power-finder/study'
    | '/api/power-finder/viewport'
    | '/api/power-finder/tile/$z/$x/$y'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activation'
    | '/data-centres'
    | '/data-sources'
    | '/demo'
    | '/energy-storage'
    | '/evidence'
    | '/evidence-review'
    | '/hydrogen-industry'
    | '/operations'
    | '/pilot'
    | '/pilot-ready'
    | '/pilot-requests'
    | '/portfolio'
    | '/power-finder'
    | '/reports'
    | '/service'
    | '/synthetic-network-study'
    | '/validation-case'
    | '/activation/$id'
    | '/assessments/$id'
    | '/assessments/new'
    | '/capacity-dossiers/$id'
    | '/operations/$id'
    | '/operator-review/$id'
    | '/pilot-case/$id'
    | '/portfolio/$id'
    | '/submission-package/$id'
    | '/api/power-finder/scenario'
    | '/api/power-finder/study'
    | '/api/power-finder/viewport'
    | '/api/power-finder/tile/$z/$x/$y'
  id:
    | '__root__'
    | '/'
    | '/activation'
    | '/data-centres'
    | '/data-sources'
    | '/demo'
    | '/energy-storage'
    | '/evidence'
    | '/evidence-review'
    | '/hydrogen-industry'
    | '/operations'
    | '/pilot'
    | '/pilot-ready'
    | '/pilot-requests'
    | '/portfolio'
    | '/power-finder'
    | '/reports'
    | '/service'
    | '/synthetic-network-study'
    | '/validation-case'
    | '/activation/$id'
    | '/assessments/$id'
    | '/assessments/new'
    | '/capacity-dossiers/$id'
    | '/operations/$id'
    | '/operator-review/$id'
    | '/pilot-case/$id'
    | '/portfolio/$id'
    | '/submission-package/$id'
    | '/api/power-finder/scenario'
    | '/api/power-finder/study'
    | '/api/power-finder/viewport'
    | '/api/power-finder/tile/$z/$x/$y'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivationRoute: typeof ActivationRouteWithChildren
  DataCentresRoute: typeof DataCentresRoute
  DataSourcesRoute: typeof DataSourcesRoute
  DemoRoute: typeof DemoRoute
  EnergyStorageRoute: typeof EnergyStorageRoute
  EvidenceRoute: typeof EvidenceRoute
  EvidenceReviewRoute: typeof EvidenceReviewRoute
  HydrogenIndustryRoute: typeof HydrogenIndustryRoute
  OperationsRoute: typeof OperationsRouteWithChildren
  PilotRoute: typeof PilotRoute
  PilotReadyRoute: typeof PilotReadyRoute
  PilotRequestsRoute: typeof PilotRequestsRoute
  PortfolioRoute: typeof PortfolioRouteWithChildren
  PowerFinderRoute: typeof PowerFinderRoute
  ReportsRoute: typeof ReportsRoute
  ServiceRoute: typeof ServiceRoute
  SyntheticNetworkStudyRoute: typeof SyntheticNetworkStudyRoute
  ValidationCaseRoute: typeof ValidationCaseRoute
  AssessmentsIdRoute: typeof AssessmentsIdRoute
  AssessmentsNewRoute: typeof AssessmentsNewRoute
  CapacityDossiersIdRoute: typeof CapacityDossiersIdRoute
  OperatorReviewIdRoute: typeof OperatorReviewIdRoute
  PilotCaseIdRoute: typeof PilotCaseIdRoute
  SubmissionPackageIdRoute: typeof SubmissionPackageIdRoute
  ApiPowerFinderScenarioRoute: typeof ApiPowerFinderScenarioRoute
  ApiPowerFinderStudyRoute: typeof ApiPowerFinderStudyRoute
  ApiPowerFinderViewportRoute: typeof ApiPowerFinderViewportRoute
  ApiPowerFinderTileZXYRoute: typeof ApiPowerFinderTileZXYRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/validation-case': {
      id: '/validation-case'
      path: '/validation-case'
      fullPath: '/validation-case'
      preLoaderRoute: typeof ValidationCaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/synthetic-network-study': {
      id: '/synthetic-network-study'
      path: '/synthetic-network-study'
      fullPath: '/synthetic-network-study'
      preLoaderRoute: typeof SyntheticNetworkStudyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service': {
      id: '/service'
      path: '/service'
      fullPath: '/service'
      preLoaderRoute: typeof ServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/power-finder': {
      id: '/power-finder'
      path: '/power-finder'
      fullPath: '/power-finder'
      preLoaderRoute: typeof PowerFinderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pilot-requests': {
      id: '/pilot-requests'
      path: '/pilot-requests'
      fullPath: '/pilot-requests'
      preLoaderRoute: typeof PilotRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pilot-ready': {
      id: '/pilot-ready'
      path: '/pilot-ready'
      fullPath: '/pilot-ready'
      preLoaderRoute: typeof PilotReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pilot': {
      id: '/pilot'
      path: '/pilot'
      fullPath: '/pilot'
      preLoaderRoute: typeof PilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations': {
      id: '/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof OperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hydrogen-industry': {
      id: '/hydrogen-industry'
      path: '/hydrogen-industry'
      fullPath: '/hydrogen-industry'
      preLoaderRoute: typeof HydrogenIndustryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence-review': {
      id: '/evidence-review'
      path: '/evidence-review'
      fullPath: '/evidence-review'
      preLoaderRoute: typeof EvidenceReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence': {
      id: '/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof EvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/energy-storage': {
      id: '/energy-storage'
      path: '/energy-storage'
      fullPath: '/energy-storage'
      preLoaderRoute: typeof EnergyStorageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-sources': {
      id: '/data-sources'
      path: '/data-sources'
      fullPath: '/data-sources'
      preLoaderRoute: typeof DataSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-centres': {
      id: '/data-centres'
      path: '/data-centres'
      fullPath: '/data-centres'
      preLoaderRoute: typeof DataCentresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activation': {
      id: '/activation'
      path: '/activation'
      fullPath: '/activation'
      preLoaderRoute: typeof ActivationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submission-package/$id': {
      id: '/submission-package/$id'
      path: '/submission-package/$id'
      fullPath: '/submission-package/$id'
      preLoaderRoute: typeof SubmissionPackageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/$id': {
      id: '/portfolio/$id'
      path: '/$id'
      fullPath: '/portfolio/$id'
      preLoaderRoute: typeof PortfolioIdRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/pilot-case/$id': {
      id: '/pilot-case/$id'
      path: '/pilot-case/$id'
      fullPath: '/pilot-case/$id'
      preLoaderRoute: typeof PilotCaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator-review/$id': {
      id: '/operator-review/$id'
      path: '/operator-review/$id'
      fullPath: '/operator-review/$id'
      preLoaderRoute: typeof OperatorReviewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations/$id': {
      id: '/operations/$id'
      path: '/$id'
      fullPath: '/operations/$id'
      preLoaderRoute: typeof OperationsIdRouteImport
      parentRoute: typeof OperationsRoute
    }
    '/capacity-dossiers/$id': {
      id: '/capacity-dossiers/$id'
      path: '/capacity-dossiers/$id'
      fullPath: '/capacity-dossiers/$id'
      preLoaderRoute: typeof CapacityDossiersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessments/new': {
      id: '/assessments/new'
      path: '/assessments/new'
      fullPath: '/assessments/new'
      preLoaderRoute: typeof AssessmentsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessments/$id': {
      id: '/assessments/$id'
      path: '/assessments/$id'
      fullPath: '/assessments/$id'
      preLoaderRoute: typeof AssessmentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activation/$id': {
      id: '/activation/$id'
      path: '/$id'
      fullPath: '/activation/$id'
      preLoaderRoute: typeof ActivationIdRouteImport
      parentRoute: typeof ActivationRoute
    }
    '/api/power-finder/viewport': {
      id: '/api/power-finder/viewport'
      path: '/api/power-finder/viewport'
      fullPath: '/api/power-finder/viewport'
      preLoaderRoute: typeof ApiPowerFinderViewportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/power-finder/study': {
      id: '/api/power-finder/study'
      path: '/api/power-finder/study'
      fullPath: '/api/power-finder/study'
      preLoaderRoute: typeof ApiPowerFinderStudyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/power-finder/scenario': {
      id: '/api/power-finder/scenario'
      path: '/api/power-finder/scenario'
      fullPath: '/api/power-finder/scenario'
      preLoaderRoute: typeof ApiPowerFinderScenarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/power-finder/tile/$z/$x/$y': {
      id: '/api/power-finder/tile/$z/$x/$y'
      path: '/api/power-finder/tile/$z/$x/$y'
      fullPath: '/api/power-finder/tile/$z/$x/$y'
      preLoaderRoute: typeof ApiPowerFinderTileZXYRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ActivationRouteChildren {
  ActivationIdRoute: typeof ActivationIdRoute
}

const ActivationRouteChildren: ActivationRouteChildren = {
  ActivationIdRoute: ActivationIdRoute,
}

const ActivationRouteWithChildren = ActivationRoute._addFileChildren(
  ActivationRouteChildren,
)

interface OperationsRouteChildren {
  OperationsIdRoute: typeof OperationsIdRoute
}

const OperationsRouteChildren: OperationsRouteChildren = {
  OperationsIdRoute: OperationsIdRoute,
}

const OperationsRouteWithChildren = OperationsRoute._addFileChildren(
  OperationsRouteChildren,
)

interface PortfolioRouteChildren {
  PortfolioIdRoute: typeof PortfolioIdRoute
}

const PortfolioRouteChildren: PortfolioRouteChildren = {
  PortfolioIdRoute: PortfolioIdRoute,
}

const PortfolioRouteWithChildren = PortfolioRoute._addFileChildren(
  PortfolioRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivationRoute: ActivationRouteWithChildren,
  DataCentresRoute: DataCentresRoute,
  DataSourcesRoute: DataSourcesRoute,
  DemoRoute: DemoRoute,
  EnergyStorageRoute: EnergyStorageRoute,
  EvidenceRoute: EvidenceRoute,
  EvidenceReviewRoute: EvidenceReviewRoute,
  HydrogenIndustryRoute: HydrogenIndustryRoute,
  OperationsRoute: OperationsRouteWithChildren,
  PilotRoute: PilotRoute,
  PilotReadyRoute: PilotReadyRoute,
  PilotRequestsRoute: PilotRequestsRoute,
  PortfolioRoute: PortfolioRouteWithChildren,
  PowerFinderRoute: PowerFinderRoute,
  ReportsRoute: ReportsRoute,
  ServiceRoute: ServiceRoute,
  SyntheticNetworkStudyRoute: SyntheticNetworkStudyRoute,
  ValidationCaseRoute: ValidationCaseRoute,
  AssessmentsIdRoute: AssessmentsIdRoute,
  AssessmentsNewRoute: AssessmentsNewRoute,
  CapacityDossiersIdRoute: CapacityDossiersIdRoute,
  OperatorReviewIdRoute: OperatorReviewIdRoute,
  PilotCaseIdRoute: PilotCaseIdRoute,
  SubmissionPackageIdRoute: SubmissionPackageIdRoute,
  ApiPowerFinderScenarioRoute: ApiPowerFinderScenarioRoute,
  ApiPowerFinderStudyRoute: ApiPowerFinderStudyRoute,
  ApiPowerFinderViewportRoute: ApiPowerFinderViewportRoute,
  ApiPowerFinderTileZXYRoute: ApiPowerFinderTileZXYRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
